name: neoflex
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1  # Последняя стабильная версия
  form_builder_validators: ^11.1.2
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/robot.png
    - assets/img/
    - assets/articles/
    - assets/data/
    - assets/sounds/
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"
  android_adaptive_icon_background: "#FFFFFF"
  android_adaptive_icon_foreground: "assets/icons/icon_foreground.png"