name: neoflex
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1  # Последняя стабильная версия
  form_builder_validators: ^11.1.2
  sqflite: ^2.3.0
  path: ^1.8.3  # Рабочая версия для Flutter 3.x


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/robot.png
  uses-material-design: true
